title: escowles.github.io
email: escowles@ticklefish.org
url: "https://escowles.github.io"
twitter_username: escowles
github_username:  escowles

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title
