title: asdf
email: escowles@ticklefish.org
#baseurl: "/asdf" # the subpath of your site, e.g. /blog
url: "https://escowles.github.io"
twitter_username: escowles
github_username:  escowles

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title
