# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: asdf
email: escowles@ticklefish.org
description: >
  not really sure, but whatever comes to mind.  maybe i'll put my github
  cheat sheet here?  maybe i'll post links to the stackoverflow answers i find
  useful...
baseurl: "/asdf" # the subpath of your site, e.g. /blog
url: "https://escowles.github.io"
twitter_username: escowles
github_username:  escowles

# Build settings
markdown: kramdown
