title: asdf
email: escowles@ticklefish.org
baseurl: "/asdf"
url: "https://escowles.github.io"
twitter_username: escowles
github_username:  escowles

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title
